name: pr-and-push-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 19.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run TS checks
        run: npm run check
      - name: Run tests
        run: npm run test
  e2e-tests:
    runs-on: ubuntu-latest
    container:
      image: neo4j:enterprise
      env:
        NEO4J_AUTH: neo4j/password
        NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      ports:
        - 7687:7687
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Copy .env file to use for integration tests
        run: cp packages/introspection/.env.example packages/introspection/.env
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test:integration
